version: '3.8'

services:
  db:
    image: postgres:15
    container_name: spondy_db
    environment:
      POSTGRES_USER: spondy_admin
      POSTGRES_PASSWORD: spondy_password
      POSTGRES_DB: spondy_travel_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  